name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Cypress Environment Variables
        run: echo "CYPRESS_EXPERIMENTAL_MEMORY_MANAGEMENT=true" >> $GITHUB_ENV

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          DEBUG: cypress:*
          
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos