name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        continue-on-error: true

      - name: Upload Cypress test results
        uses: actions/upload-artifact@v4
        with:
          name: cypress-test-results
          path: cypress/results/*.json

      - name: Upload Cypress screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots